[package]
name = "session-telemetry-cli"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "session-telemetry"
path = "src/main.rs"

[dependencies]
session-telemetry-adb.workspace = true
clap.workspace = true

[lib]
name = "session_telemetry_cli"
path = "src/lib.rs"
